// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import company "github.com/devit-tel/gogo-blueprint/domain/company"
import context "context"
import goerror "github.com/devit-tel/goerror"
import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, companyId
func (_m *Repository) Get(ctx context.Context, companyId string) (*company.Company, goerror.Error) {
	ret := _m.Called(ctx, companyId)

	var r0 *company.Company
	if rf, ok := ret.Get(0).(func(context.Context, string) *company.Company); ok {
		r0 = rf(ctx, companyId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*company.Company)
		}
	}

	var r1 goerror.Error
	if rf, ok := ret.Get(1).(func(context.Context, string) goerror.Error); ok {
		r1 = rf(ctx, companyId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(goerror.Error)
		}
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *Repository) Save(ctx context.Context, _a1 *company.Company) goerror.Error {
	ret := _m.Called(ctx, _a1)

	var r0 goerror.Error
	if rf, ok := ret.Get(0).(func(context.Context, *company.Company) goerror.Error); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(goerror.Error)
		}
	}

	return r0
}
